adding turkish language support to the theme
vuepress-theme-hope/vuepress-theme-hope pull request #2357
Opened 2022-10-31 18:22 UTC by ngurmen

- added "/tr/" sections to all relevant locales.ts files
- added packages/shared/src/node/utils/dayjs/tr.ts for day and month names

2022-11-01 06:27 UTC, Mister-Hope requested changes

2022-11-01 06:27 UTC, Mister-Hope commented on packages/shared/src/node/utils/dayjs/tr.ts
> +export const loadEnLocale = (extendeddayjs: typeof dayjs): void => {
```suggestion
export const loadTrLocale = (extendeddayjs: typeof dayjs): void => {
```

2022-11-01 06:31 UTC, Mister-Hope commented
You doesnot tick "Allow edits from maintainers", so I am not be able to update your pr.

You need to:

1. Add tr in `vuepress-shared` so that we can recoginze it: https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/packages/shared/src/node/locales/config.ts
2. Add theme locales in https://github.com/vuepress-theme-hope/vuepress-theme-hope/tree/main/packages/theme/src/node/locales and do not foget to add it to index.ts
3. To let dayjs workwell, this file needs an update: https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/packages/shared/src/node/utils/dayjs/index.ts

2022-11-01 17:23 UTC, ngurmen commented
@Mister-Hope , thanks for your feedback.  I updated all files.  There is just one file we are still working on.  When finished I will re-request your review.  Just wanted to check "Allow edits from maintainers" but I don't see that check box as shown in the image below.  Not sure why.

![image](https://user-images.githubusercontent.com/70996543/199296370-f485553a-1b73-423d-8d2e-f5ce42451c32.png)

I did not use this workflow of creating a PR from a fork before.  I thought maybe you have some ideas why that one is not available.   Thanks.

2022-11-02 04:22 UTC, Mister-Hope commented
There should be a checkbox when you opening a PR.

2022-11-02 12:23 UTC, Mister-Hope commented on packages/theme/src/node/locales/tr.ts
> +    // eslint-disable-next-line @typescript-eslint/naming-convention
```suggestion
```

2022-11-03 02:37 UTC, Mister-Hope commented
Could you please pass the linter?

2022-11-03 19:13 UTC, ngurmen commented
fixed the issues, it should now pass the linter.  thx.

2022-11-04 04:57 UTC, merged