Update projects.md
vuepress-theme-hope/vuepress-theme-hope pull request #3184
Opened 2023-06-02 15:13 UTC by XXXWeii

添加博客案例

2023-06-02 15:15 UTC, XXXWeii commented
Mr.Hope看看我的成果哈哈哈哈哈

2023-06-03 17:05 UTC, Mister-Hope requested changes

2023-06-03 17:05 UTC, Mister-Hope commented on docs/theme/src/zh/demo/projects.md
> +- name: XXXWeii
Wrong indent
```suggestion
  - name: XXXWeii 
```

2023-06-03 17:06 UTC, Mister-Hope commented
Also why do you think you should put you things before others?

2023-06-03 17:07 UTC, Mister-Hope commented on docs/theme/src/zh/demo/projects.md
> +   preview: https://xxxweii.github.io/XXXWeiiBlog/assets/images/XXXWeii.png
```suggestion
   desc: 带着思念期待着下次相见 
    logo: https://xxxweii.github.io/XXXWeiiBlog/logo.jpg
    url: https://xxxweii.github.io/XXXWeiiBlog 
    repo: https://github.com/XXXWeii/XXXWeiiBlog 
    preview: https://xxxweii.github.io/XXXWeiiBlog/assets/images/XXXWeii.png 
```

2023-06-03 17:07 UTC, Mister-Hope commented on docs/theme/src/zh/demo/projects.md
> +   desc: 带着思念期待着下次相见
```suggestion
    desc: 带着思念期待着下次相见 
```

2023-06-04 02:42 UTC, closed without merging