feat(auto-catalog): add hideCategory option and use ol for index option
vuepress-theme-hope/vuepress-theme-hope pull request #3367
Opened 2023-08-13 10:18 UTC by zfben

This pull request work for https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/3333

Add hideCategory option and use `ol` for index option.

2023-08-19 04:56 UTC, Mister-Hope commented on docs/auto-catalog/src/config.md
> +### hideCategory
It's better to be `hideHeading` or `hideTitle`

2023-08-19 04:57 UTC, Mister-Hope commented on packages/auto-catalog/src/client/components/AutoCatalog.ts
> +                      props.index ? "ol" : "ul",
Are nesting ol markers be `1.1` `1.1.1` in all kinds of devices? I think not, the styles needs to be handled correctly.

2023-08-19 04:58 UTC, Mister-Hope requested changes
Fix those. Also zh docs are missing

2023-08-29 05:18 UTC, Mister-Hope commented
Is this PR still under development? @zfben

2023-08-29 07:04 UTC, zfben commented
> Is this PR still under development? @zfben

I'm busy these days, I will do it later.

2023-09-17 03:34 UTC, zfben commented
@Mister-Hope I have updated code and add indexType to let users can choose ul or ol by themselves.

2023-10-09 09:32 UTC, Mister-Hope commented
Sorry but  I cleaned up all the deps PR at main, could.you make a rebase?

2023-10-10 03:59 UTC, zfben commented
@Mister-Hope done

2023-10-10 07:01 UTC, merged