fix(comment2): artalk ui don't load where route change
vuepress-theme-hope/vuepress-theme-hope pull request #3550
Opened 2023-10-18 08:32 UTC by mmdapl

修复artalk评论系统UI界面不加载问题

复现方式：
- 在demo中切换路由，发现会请求artalk接口,但是UI界面不显示，但是重新刷新页面会显示
- 很明显能感觉到首次进入，无评论UI，很奇怪

解决方式：
- 监听路由，对于路由变化或者刷新等操作，加载Artalk系统的UI界面

2023-10-24 05:48 UTC, Mister-Hope commented
This is not a valid fix in my mind, the identifier is supported to be customizable, and it's default to route path.

A valid fix is that why the watch trigger not called when switching to a new page.

2023-10-24 05:49 UTC, Mister-Hope requested changes
See comment above

2023-10-25 08:07 UTC, mmdapl commented
> This is not a valid fix in my mind, the identifier is supported to be customizable, and it's default to route path.
> 
> A valid fix is that why the watch trigger not called when switching to a new page.

其实identifier是监听到了，并且callback方法也能回调，但我我目前还没有找到为什么对调执行的函数无法驱动视图层面展示,

但通过监听router.path 就可以驱动展示。我在想是不是跟vue3的组件加载有关系？

2023-10-25 08:23 UTC, Mister-Hope commented
也许吧，我在求职最近比较忙，你可以先研究研究(⑅•͈ᴗ•͈).:*♡

2023-10-25 09:53 UTC, Mister-Hope commented
你把组件的div加一个key试一下？

2023-10-25 10:01 UTC, mmdapl commented
> 你把组件的div加一个key试一下？

这个我尝试过，不太行

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/40396940/86401d93-b6a6-4dd2-ad45-da3dab042053)

我非常疑惑的是，两个watch监听，在首次artalk评论渲染出来后，切换路由，这个artalkContainer值不一样。 

正式因为props的监听得到的artalkContainer值缺少class类

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/40396940/1ac7d674-fed7-4ad2-be8e-84dc6ddae201)


导致artalk初始化是el找不到，我想应该是原因

2023-10-25 11:41 UTC, Mister-Hope commented
哦，watchOptions 加个flush post 试试

2023-10-25 12:47 UTC, mmdapl commented
> 哦，watchOptions 加个flush post 试试

有尝试过，没太大用 监听props属性的回调里面，el是div没有css类

2023-10-26 17:59 UTC, Mister-Hope commented
Can you test this https://github.com/vuepress-theme-hope/vuepress-theme-hope/tree/artalk ?

It would be great if you can provide an artalk server for me to debug.

2023-10-27 01:04 UTC, Mister-Hope commented
你要方便的话给我个artalk地址我现在测测

2023-10-27 02:58 UTC, mmdapl commented
Rong姐姐好可爱
***@***.***



&nbsp;
哈喽，您主库的artalk分支，我有尝试过，还是有点问题.




您可以用我的artalk服务器地址：
defineArtalkConfig({
  provider: "Artalk",
  server:"https://test.142vip.cn/",
  site:'JavaScriptCollection',
})



测试完成后，麻烦和我说下，我把跨域限制和域名代理关掉。 当然，您也直接Pull我的分支进行测试， 分支地址：https://github.com/mmdapl/vuepress-theme-hope/tree/fix/comment-artalk




麻烦大佬了，期待您的回复


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vuepress-theme-hope/vuepress-theme-hope"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月27日(星期五) 上午9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vuepress-theme-hope/vuepress-theme-hope] fix(comment2): artalk ui don't load where route change (PR #3550)





 
你要方便的话给我个artalk地址我现在测测
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-10-27 03:00 UTC, mmdapl commented
> Can you test this https://github.com/vuepress-theme-hope/vuepress-theme-hope/tree/artalk ?
> 
> It would be great if you can provide an artalk server for me to debug.

这个我测试过，有点问题

2023-10-27 03:01 UTC, mmdapl commented
> 你要方便的话给我个artalk地址我现在测测

哈喽，您看看邮箱，我发您邮箱上了, 您看看您邮箱：[vuepress-theme-hope@noreply.github.com](mailto:vuepress-theme-hope@noreply.github.com)

2023-10-27 03:16 UTC, Mister-Hope commented
Mister-hope@outlook.com

2023-10-27 03:22 UTC, mmdapl commented
> [Mister-hope@outlook.com](mailto:Mister-hope@outlook.com)

OK，发送过去了

2023-11-16 03:44 UTC, mmdapl commented
> 你要方便的话给我个artalk地址我现在测测

后面有新的进展嘛？ 我尝试过很久，只想到了这种处理方式。 先merge掉叭，让artalk评论先用起来，后面再进一步优化？

2023-12-18 04:30 UTC, closed without merging