feat(theme): add more social media icon & fix
vuepress-theme-hope/vuepress-theme-hope pull request #3654
Opened 2023-11-24 07:04 UTC by CN-ycx

2023-11-24 10:13 UTC, Mister-Hope reviewed
All icons should be added with a class `icon $name-icon`, e.g.: `icon baidu-icon`.

This is for style control consideration

2023-11-24 10:13 UTC, Mister-Hope commented on packages/theme/templates/socialMediaIcons/twitch.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" viewBox="0 0 1024 1024"><circle cx="512" cy="512" r="512" fill="#9147FF"/><path fill="#FFF" d="M366 220 262 324v376h125v104l104-104h84l187
Hi there, you should try to compress these icons, e.g.: remove `xml:space="preserve"` and `<animate>` tag:

```suggestion
<svg xmlns="http://www.w3.org/2000/svg" class="icon twitch-icon" viewBox="0 0 1024 1024"><circle cx="512" cy="512" r="512" fill="#9147FF"/><path fill="#FFF" d="M366 220 262 324v376h125v104l104-104h84l187-188V220z"/><path fill="#9147FF" d="m637 575 83-84V262H387v313h83v83l84-83z"/><path fill="#FFF" d="M512 345h42v125h-42V345zm146 0v125h-42V345h42z"/></svg>
```

2023-11-24 10:15 UTC, Mister-Hope requested changes
See comment above, related docs needs to be updated as well

2023-11-24 14:42 UTC, CN-ycx commented
Some of icons from official websites, and that can't be compress, now trying redraw them. I has already used a similar compression tool like svgo to compress before submitting, and I'm still working on it

2023-11-27 02:58 UTC, Mister-Hope approved these changes
LGTM

2023-11-27 03:01 UTC, merged

2023-12-05 05:41 UTC, Mister-Hope commented
@CN-ycx Could you update twitter icon in share component? https://plugin-components.vuejs.press/guide/utilities/share.html

2023-12-06 09:14 UTC, CN-ycx commented
@Mister-Hope I noticed that in this component, some icons provide shape and icon version, and others only have icon or shape part.

Should I make shape and icon of these icons both?
Or we can import icons from social media icon like `../../../../../theme/templates/socialMediaIcons/*.svg`,
but the path is too long or illegal, maybe we can make icon as share component to use?

2023-12-06 09:24 UTC, Mister-Hope commented
The component is expected to be as slim as possible, so if you can use a shape to generate a colorful icon, then no 2 svg.

2023-12-07 01:02 UTC, CN-ycx commented
@Mister-Hope should all share icons added with a class `icon $name-icon`?