feat(components): add more share services & redraw icons
vuepress-theme-hope/vuepress-theme-hope pull request #3709
Opened 2023-12-07 14:49 UTC by CN-ycx

I plan to add more services than now, but:
Some service is not providing public share URL, or need api id, or using url scheme like `messenger://`, it hard to find.

@Mister-Hope We can discuss how to add these services, and add more later.

2023-12-07 16:55 UTC, Mister-Hope requested changes
We should also update the default value,  Um for example people will rarely share with sms.

The default value will be a bunch of popular services

2023-12-07 16:55 UTC, Mister-Hope commented on docs/components/src/zh/guide/utilities/share.md
> +    | "wordpress;
typo here

2023-12-07 16:55 UTC, Mister-Hope commented on docs/components/src/guide/utilities/share.md
> +    | "wordpress;
typo here

2023-12-08 04:16 UTC, CN-ycx commented
Work complete, most of sharing services not modify the link, but also then not provide docs.
They mostly from search results or application build-in sharing.
If necessary, I will provide link of docs for sharing services with API key requirement.

2023-12-08 10:26 UTC, merged

2023-12-08 10:29 UTC, Mister-Hope commented
Thanks, can you create another pr with https://vueuse.org/core/useShare/#useshare?

This could be a new root component called `<ShareButton>`, which it should be placed above the backtotop button.

2023-12-08 10:52 UTC, Mister-Hope commented
> We should also update the default value, Um for example people will rarely share with sms.
>
> The default value will be a bunch of popular services

<img width="527" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/9c8b64de-d6d0-43b3-98bb-42916ee3dd4b">

I did not see the above changes? My suggestions is to update here, it's not reasonable to have a full list of services by default which contains very uncommon ones.

You can try to look around for popular websites to see their share services and leave 5-8 popular service here.

Note: JSDoc of the option should be updated as well besides docs about the default fallback value.

2023-12-08 10:55 UTC, Mister-Hope commented
And again, thanks for your contirbution😉

2023-12-08 11:06 UTC, CN-ycx commented
It's my fault, didn't understand so I only modified the order, sorry😰